added option to skip bad sectors in mkudffs
pali/udftools pull request #11
Opened 2017-12-31 01:50 UTC by ganboing

Hi Pali,

Would you mind take a look at this change? I've added a option to skip bad sectors in mkudffs. It allows disc to be formatted even if some sectors has worn out. It can also be used for to reserve those sectors. Not sure if utilizing the "BAD" enum is the current approach.

Bo

2017-12-31 09:26 UTC, pali commented
"BAD" enum is unused, so it is ok. But this code is not enough. If there are bad sectors in partition data area (PSPACE) then it needs to be properly splitted. Also to prevent allocation of bad sectors by UDF filesystem drivers, it is needed to put those bad sectors into system stream "*UDF Non-Allocatable Space". See section 3.3.7.2 in UDF specification. And about API, what about using rather file with bad sectors, like in mke2fs? Then it would be easier also integration with `badblocks` tool which find bad sectors automatically.

2018-01-01 02:06 UTC, ganboing commented
Thanks for your reply. I didn't even think about PSPACE, as I'm quite new to UDF spec. The primary reason for this is to relocate LVID and other potentially frequently overwritten sectors. When used in Windows, I noticed that it placed the LVID at sector 64 on my DVD-RW. After some stress testing, sector 64-79 is no longer read/writable. With the patch, I'm able to advise mkudffs not to put LVID on or close to the bad sectors, and the disc can be reused.

I'll have to read more about UDF Non-Allocatable Space to have a proper way to mark these sectors per spec. It's not going to be very soon for a new PR.

2018-01-02 12:37 UTC, pali commented
Even your current algorithm for marking bad blocks would not work when you specify some bad block which is in normal partition space. As currently mkudffs can work only with continuous partition space, marking some block as bad would result in half of disk to be unused space.

I understand your motivation (there is no problem to put LVID on other blocks), but patches in current form are not ready for merging.

2018-01-05 21:15 UTC, pali requested changes
Marking as request changes.

2018-04-22 13:54 UTC, pali commented
Are you going to rework/fix your changes?

2018-09-03 08:00 UTC, pali commented
Closing for inactivity.

2018-09-03 08:00 UTC, closed without merging